### ISSUE TITLE
Error in `whereRelated` for empty relationships

### ISSUE THREAD

**Issue by bewildergeist** [blue-chip-js/blue-chip#28]
According to the [JSON API spec](https://jsonapi.org/format/#document-resource-object-linkage) a an empty to-one relationship is represented by `{data: null}`. But `blue-chip` [doesn't currently handle this](https://github.com/blue-chip-js/blue-chip/blob/b504b9959b06b414cf99c68c14cd7e4e48009c10/src/Query.js#L116), resulting in a `null is not an object` error:

![null-error-relationship](https://user-images.githubusercontent.com/121186/60098354-a4898100-9755-11e9-9819-a8d8366cf9b6.png)

**Comment by mfpiccolo** [comment]
Thanks for reporting @bewildergeist. Can you create a failing test and I can fix it?

**Comment by bewildergeist** [comment]
@mfpiccolo I've added a failing test and a simple fix in #30, but might be overlooking other related issues, as I'm not deep in the blue-chip codebase yet, so please change or expand upon it 🙏

**Comment by mfpiccolo** [comment]
Thanks! I merged and will do a release soon.
